---
title: "Tema 3. Mini-práctica"
author:
- 'Prof.: Pedro Albarrán'
- 'Prof.: Alberto Pérez'
date: "Universidad de Alicante, Curso 2020/21"
output:
  html_document: default
---

<!--
Reemplaza el número en `mi.DNI` por los números de tu DNI (o NIE) y ejecuta *todo* el siguiente código de una vez. Obtendrás un nombre para usar posteriormente.
```{r echo=T, eval=FALSE}
mi.DNI <- 1234567890   
set.seed(mi.DNI)  
babynames %>% 
        group_by(name) %>% 
        summarise(pr=sum(prop)) %>% 
        arrange(desc(pr)) %>% 
        head(100) %>% 
        filter(row_number()==round(runif(1,1,100))) %>% 
        select(name)
```
Escribe el código que responda a las preguntas de cada de los siguientes apartados.
-->

# Mini-Práctica

Escribe un archivo .R con el código necesario para responder a las siguientes preguntas. La transformación de datos será una línea con comandos anidados.


El nombre del archivo DEBE EMPEZAR con vuestro número de DNI (el resto es libre): ej., 

> 12345678_T03.R

Finalmente, rellenad este [FORMULARIO](https://docs.google.com/forms/d/e/1FAIpQLSe5A8m0SfgQzl5DXva66bk4m0wVBE1QCyDagKdL_Ko0xyiVQQ/viewform) con vuestros datos y subid


# Preguntas

1. Elige un nombre y encontrar el año en que fue usado con más frecuencia.

<!--
2. ¿Qué nombre fue el más popular en el año del apartado anterior?
-->

2. ¿En qué año hubo más nacimientos y cuántos fueron?
  
3. Encontar los diez nombres más populares de la década de los 1990s.

<!--  
4. Obtener un conjunto de datos (`data frame`) con tres variables: cada nombre, el primer año en que aparece y el último año en que aparece.
-->


<!--  
3. In which year was that name given to M and F babies most equally (i.e. closest to a 50/50 split)?


There are 15 names that have been assigned to both sexes in all 138 years. List them.
-->
  
<!--
5. Considera los nombres con al menos 1% de nacimientos en un año dado. ¿Cuál es el año más reciente en que aparece?

-->  

<!--  
It seems like there is more diversity of names now than in the past. How have the number of names used changed over time? Has it been the same for boys and girls?

  -->

<!--
Use ggplot2 and group_by() to create an interesting and informative data graphic. It need not be about babynames. Post your graphic and a short description of it to Slack.
-->

<!--More Practice (optional)

If you are looking for some more practice, try these, using the nycflights13 package.
-->

<!--
What was the daily average number of flights leaving each of the three NYC airports in 2013?

-->

4. Usando los datos del paquete `nycflights13`, calcular para cada compañía (`carrier`) el número total de vuelos, el retraso medio en la salida, el número de destinos únicos a los que vuela, y el número de aviones únicos utilizados.


5. Usando el conjunto de datos obtenido en el apartado anterior, obtener los siguientes gráficos:

    * Un gráfico de caja (`boxplot`) del retraso medio.
    
    * Un histograma del número de aviones.
    
    * La densidad del número total de vuelos.
    

<!--
Plot the distribution of average daily delay time across the entire year for each of the three airports.

Challenge: Plot the average arrival delay time as a function of the distance flown to the nearest 100 miles for each of the three airports.
-->

